/**
 * Application Constants
 * shiro-api - Cloudflare Worker API Gateway
 */

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
};

export const ERROR_CODES = {
  BAD_REQUEST: "BAD_REQUEST",
  MISSING_PARAM: "MISSING_PARAMETER",
  INVALID_PARAM: "INVALID_PARAMETER",
  INVALID_URL: "INVALID_URL",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  PROVIDER_ERROR: "PROVIDER_ERROR",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  INTERNAL_ERROR: "INTERNAL_SERVER_ERROR",
  CACHE_ERROR: "CACHE_ERROR",
  JWT_EXPIRED: "JWT_EXPIRED",
  JWT_INVALID: "JWT_INVALID",
};

export const DEFAULT_QUALITY = {
  VIDEO: "720",
  AUDIO: "128",
};

export const SUPPORTED_QUALITIES = ["360", "480", "720", "1080"];

export const PROVIDERS = {
  NAZE: "naze",
};

export const API_VERSION = "1.0.0";
